#!/bin/bash

sudo pacman -S --noconfirm --needed - < package_list.txt

git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

chsh -s $(which fish)
